const commentsBanhBao = [
  "Trông ngon quá!",
  "Cho mình order 1 phần nhé!",
  "Bánh bao này có vị gì vậy?",
  "Mua ở đâu vậy ad?",
  "Có giao hàng không shop?",
  "Giá bao nhiêu 1 cái vậy?",
  "Mình muốn thử món này quá!",
  "Có ai đã ăn chưa, review chút nào!",
  "Bánh này làm từ nguyên liệu gì thế?",
  "Đẹp và ngon, kết hợp tuyệt vời!",
  "Có giảm giá không ad?",
  "Bánh này có chay không?",
  "Hương vị trông hấp dẫn quá!",
  "Shop có ship đến Vinhomes Smart City không?",
  "Ngon quá, mình muốn ăn thử!",
  "Mua 5 cái được giảm giá không?",
  "Bánh bao màu sắc đẹp quá!",
  "Có bán lẻ không ad?",
  "Nhìn thích quá, muốn ăn thử ngay!",
  "Hấp dẫn thật sự!",
  "Bánh này tự làm à?",
  "Món này là đặc sản ở đâu vậy?",
  "Có thể đặt trước không ad?",
  "Bánh bao kiểu mới lạ quá!",
  "Chắc ngon lắm, phải thử mới được!",
  "Shop có hotline không?",
  "Có bán số lượng lớn không?",
  "Bánh bao này có loại nào khác không?",
  "Mua 1 cặp bao nhiêu tiền vậy?",
  "Bánh bao này có vị gì đặc biệt không?",
  "Mua 10 cái có khuyến mãi gì không?",
  "Mình muốn đặt ngay!",
  "Hình ảnh đẹp quá!",
  "Có nhận ship nội thành không?",
  "Bánh bao này nhân gì vậy?",
  "Thấy ngon quá, muốn thử ngay!",
  "Ngon mà nhìn cũng hấp dẫn nữa!",
  "Mình muốn đặt ngay, cho mình thông tin nhé!",
  "Bánh bao đẹp và ngon quá!",
  "Mua nhiều có được giảm giá không ad?",
  "Mua 3 cái có ưu đãi gì không?",
  "Bánh bao này có gì đặc biệt vậy ad?",
  "Đẹp và ngon, mình muốn thử!",
  "Bánh bao này có vị gì?",
  "Mua nhiều có khuyến mãi gì không?",
  "Bánh bao ngon quá, phải thử mới được!",
  "Bánh bao này làm từ gì vậy?",
  "Mua 1 cặp bao nhiêu tiền?",
  "Bánh bao ngon và đẹp quá!",
  "Có nhận ship toàn quốc không?",
  "Bánh bao này nhân gì?",
  "Ngon quá, mình muốn ăn thử!",
  "Shop có bán ở khu vực Vinhomes không?",
  "Hình ảnh đẹp quá!",
  "Có nhận ship nội thành không?",
  "Bánh bao này nhân gì vậy?",
  "Thấy ngon quá, muốn thử ngay!",
  "Ngon mà nhìn cũng hấp dẫn nữa!",
  "Mình muốn đặt ngay, cho mình thông tin nhé!",
  "Bánh bao đẹp và ngon quá!",
  "Mua nhiều có được giảm giá không ad?",
  "Mua 3 cái có ưu đãi gì không?",
  "Bánh bao này có gì đặc biệt vậy ad?",
  "Đẹp và ngon, mình muốn thử!",
  "Bánh bao này có vị gì?",
  "Mua nhiều có khuyến mãi gì không?",
  "Bánh bao ngon quá, phải thử mới được!",
  "Bánh bao này làm từ gì vậy?",
  "Mua 1 cặp bao nhiêu tiền?",
  "Bánh bao ngon và đẹp quá!",
  "Có nhận ship toàn quốc không?",
  "Bánh bao này nhân gì?",
  "Ngon quá, mình muốn ăn thử!",
  "Hình ảnh đẹp quá!",
  "Có nhận ship nội thành không?",
  "Bánh bao này nhân gì vậy?",
  "Thấy ngon quá, muốn thử ngay!",
  "Ngon mà nhìn cũng hấp dẫn nữa!",
  "Mình muốn đặt ngay, cho mình thông tin nhé!",
  "Bánh bao đẹp và ngon quá!",
  "Mua nhiều có được giảm giá không ad?",
  "Mua 3 cái có ưu đãi gì không?",
  "Bánh bao này có gì đặc biệt vậy ad?",
  "Bánh bao ngon quá, mình muốn ăn thử!",
  "Có giao hàng đến Vinhomes Smart City không?",
  "Mình ở Tây Mỗ, có ship đến không?",
  "Mình muốn đặt bánh bao, cho mình thông tin nhé!",
  "Shop có nhận ship hàng trong nội thành không?",
  "Nhìn bánh bao ngon quá, muốn ăn thử!",
  "Trông ngon quá!",
  "Cho mình order 1 phần nhé!",
  "Bánh bao này có vị gì vậy?",
  "Mua ở đâu vậy ad?",
  "Có giao hàng không shop?",
  "Giá bao nhiêu 1 cái vậy?",
  "Mình muốn thử món này quá!",
  "Có ai đã ăn chưa, review chút nào!",
  "Bánh này làm từ nguyên liệu gì thế?",
  "Đẹp và ngon, kết hợp tuyệt vời!",
  "Có giảm giá không ad?",
  "Bánh này có chay không?",
  "Hương vị trông hấp dẫn quá!",
  "Shop có ship đến Hà Đông không?",
  "Ngon quá, mình muốn ăn thử!",
  "Mua 5 cái được giảm giá không?",
  "Bánh bao màu sắc đẹp quá!",
  "Có bán lẻ không ad?",
  "Nhìn thích quá, muốn ăn thử ngay!",
  "Hấp dẫn thật sự!",
  "Bánh này tự làm à?",
  "Món này là đặc sản ở đâu vậy?",
  "Có thể đặt trước không ad?",
  "Bánh bao kiểu mới lạ quá!",
  "Chắc ngon lắm, phải thử mới được!",
  "Shop có hotline không?",
  "Có bán số lượng lớn không?",
  "Bánh bao này có loại nào khác không?",
  "Mua 1 cặp bao nhiêu tiền vậy?",
  "Bánh bao này có vị gì đặc biệt không?",
  "Mua 10 cái có khuyến mãi gì không?",
  "Mình muốn đặt ngay!",
  "Hình ảnh đẹp quá!",
  "Có nhận ship nội thành không?",
  "Bánh bao này nhân gì vậy?",
  "Thấy ngon quá, muốn thử ngay!",
  "Ngon mà nhìn cũng hấp dẫn nữa!",
  "Mình muốn đặt ngay, cho mình thông tin nhé!",
  "Bánh bao đẹp và ngon quá!",
  "Mua nhiều có được giảm giá không ad?",
  "Mua 3 cái có ưu đãi gì không?",
  "Bánh bao này có gì đặc biệt vậy ad?",
  "Đẹp và ngon, mình muốn thử!",
  "Bánh bao này có vị gì?",
  "Mua nhiều có khuyến mãi gì không?",
  "Bánh bao ngon quá, phải thử mới được!",
  "Bánh bao này làm từ gì vậy?",
  "Mua 1 cặp bao nhiêu tiền?",
  "Bánh bao ngon và đẹp quá!",
  "Có nhận ship toàn quốc không?",
  "Bánh bao này nhân gì?",
  "Ngon quá, mình muốn ăn thử!",
  "Shop có bán ở khu vực Hà Đông không?",
  "Hình ảnh đẹp quá!",
  "Có nhận ship nội thành không?",
  "Bánh bao này nhân gì vậy?",
  "Thấy ngon quá, muốn thử ngay!",
  "Ngon mà nhìn cũng hấp dẫn nữa!",
  "Mình muốn đặt ngay, cho mình thông tin nhé!",
  "Bánh bao đẹp và ngon quá!",
  "Mua nhiều có được giảm giá không ad?",
  "Mua 3 cái có ưu đãi gì không?",
  "Bánh bao này có gì đặc biệt vậy ad?",
  "Đẹp và ngon, mình muốn thử!",
  "Bánh bao này có vị gì?",
  "Mua nhiều có khuyến mãi gì không?",
  "Bánh bao ngon quá, phải thử mới được!",
  "Bánh bao này làm từ gì vậy?",
  "Mua 1 cặp bao nhiêu tiền?",
  "Bánh bao ngon và đẹp quá!",
  "Có nhận ship toàn quốc không?",
  "Bánh bao này nhân gì?",
  "Ngon quá, mình muốn ăn thử!",
  "Hình ảnh đẹp quá!",
  "Có nhận ship nội thành không?",
  "Bánh bao này nhân gì vậy?",
  "Thấy ngon quá, muốn thử ngay!",
  "Ngon mà nhìn cũng hấp dẫn nữa!",
  "Mình muốn đặt ngay, cho mình thông tin nhé!",
  "Bánh bao đẹp và ngon quá!",
  "Mua nhiều có được giảm giá không ad?",
  "Mua 3 cái có ưu đãi gì không?",
  "Bánh bao này có gì đặc biệt vậy ad?",
  "Bánh bao ngon quá, mình muốn ăn thử!",
  "Có giao hàng đến Hà Đông không?",
  "Mình ở Thanh Xuân, có ship đến không?",
  "Mình muốn đặt bánh bao, cho mình thông tin nhé!",
  "Shop có nhận ship hàng trong nội thành không?",
  "Nhìn bánh bao ngon quá, muốn ăn thử!",
  "Check ib mình với ạ.",
  "Rep ib mình với bạn ơi.",
  "Ngon lắm luôn ạ. Chuẩn sầu riêng xịn sò.",
  "Còn bánh không bạn ơi?",
  "Ship xuống bao nhiêu vậy ạ?",
  "Có ship Thanh Xuân không ạ?",
  "Rep ib mình với bạn ơi.",
  "Ngon lắm, mình muốn đặt thêm.",
  "Bánh bao eatclean này có nhiều vị không?",
  "Check ib bạn ơi.",
  "Rep ib mình nhé.",
  "Mình muốn đặt bánh eatclean, rep ib nhé.",
  "Shop có giao hàng đến Thanh Xuân không?",
  "Check ib giúp mình nhé.",
  "Giá bánh bao nhân đậu đỏ bao nhiêu ạ?",
  "Rep ib mình với bạn nhé.",
  "Cho mình hỏi giá bánh bao nhân thịt ạ?",
  "Check ib mình với.",
  "Rep ib nhé, mình muốn đặt bánh.",
  "Bánh bao nhân trứng muối giá bao nhiêu?",
  "Có giao hàng đến Cầu Giấy không bạn?",
  "Check ib mình với.",
  "Rep ib mình với.",
  "Bánh bao nhân đậu xanh bao nhiêu tiền?",
  "Mình ở Đống Đa, có ship đến không?",
  "Cho mình hỏi giá bánh bao nhân gà nhé.",
  "Rep ib mình với.",
  "Check ib giúp mình với.",
  "Có giao hàng đến Ba Đình không shop?",
  "Giá bánh bao nhân thịt nướng bao nhiêu?",
  "Rep ib mình với bạn nhé.",
  "Bánh bao nhân phô mai giá sao ạ?",
  "Mình muốn đặt bánh, check ib với.",
  "Rep ib mình với.",
  "Check ib giúp mình nhé.",
  "Shop có ship đến Hoàn Kiếm không?",
  "Giá bánh bao nhân rau củ bao nhiêu ạ?",
  "Rep ib mình với.",
  "Check ib giúp mình với.",
  "Bánh bao nhân thịt gà nướng giá bao nhiêu?",
  "Cho mình hỏi giá bánh bao nhân hải sản nhé.",
  "Rep ib mình với.",
  "Check ib giúp mình nhé.",
  "Có giao hàng đến Tây Hồ không bạn?",
  "Giá bánh bao nhân trứng muối bao nhiêu?",
  "Rep ib mình với bạn nhé.",
  "Mình muốn đặt bánh, check ib với.",
  "Check ib giúp mình với.",
  "Bánh bao nhân thịt xá xíu giá sao ạ?",
  "Rep ib mình với.",
  "Có giao hàng đến Long Biên không shop?",
  "Giá bánh bao nhân đậu đỏ bao nhiêu?",
  "Check ib mình với.",
  "Rep ib giúp mình với.",
  "Mình ở Hai Bà Trưng, có ship đến không?",
  "Cho mình hỏi giá bánh bao nhân thịt ạ?",
  "Check ib giúp mình với.",
  "Rep ib mình với.",
  "Giá bánh bao nhân đậu xanh bao nhiêu ạ?",
  "Có giao hàng đến Hoàng Mai không bạn?",
  "Check ib giúp mình nhé.",
  "Rep ib mình với bạn nhé.",
  "Giá bánh bao nhân thịt gà nướng bao nhiêu?",
  "Mình muốn đặt bánh, check ib với.",
  "Rep ib giúp mình với.",
  "Có giao hàng đến Từ Liêm không shop?",
  "Giá bánh bao nhân trứng muối bao nhiêu ạ?",
  "Check ib giúp mình với.",
  "Rep ib mình với.",
  "Mình muốn hỏi giá bánh bao nhân thịt nhé.",
  "Có ship đến Gia Lâm không bạn?",
  "Check ib giúp mình với.",
  "Rep ib mình với bạn nhé.",
  "Giá bánh bao nhân rau củ bao nhiêu?",
  "Mình muốn đặt bánh, check ib với.",
  "Rep ib giúp mình với.",
  "Bánh bao nhân phô mai giá sao ạ?",
  "Có ship đến Hoài Đức không bạn?",
  "Check ib giúp mình với.",
  "Rep ib mình với.",
  "Giá bánh bao nhân thịt nướng bao nhiêu?",
  "Cho mình hỏi giá bánh bao nhân đậu đỏ nhé.",
  "Check ib giúp mình với.",
  "Rep ib mình với bạn nhé.",
  "Giá bánh bao nhân trứng muối bao nhiêu?",
  "Mình muốn đặt bánh, check ib với.",
  "Rep ib giúp mình với.",
  "Có ship đến Đông Anh không bạn?",
  "Check ib giúp mình với.",
  "Rep ib mình với.",
  "Giá bánh bao nhân đậu xanh bao nhiêu?",
  "Cho mình hỏi giá bánh bao nhân thịt gà nhé.",
  "Check ib giúp mình với.",
  "Rep ib mình với bạn nhé.",
  "Giá bánh bao nhân thịt xá xíu bao nhiêu?",
  "Mình muốn đặt bánh, check ib với.",
  "Rep ib giúp mình với.",
  "Có ship đến Thanh Trì không bạn?",
];

const commentsShopeeSale = [
  "Hết gòi",
  "Ngon",
  "Woww đỉnh quá",
  "Ngon zị",
  "Có má cho ng mới k ạ",
  "Vào muộn nên hết mất tiu",
  "Mua kẹt ship còn 2k heheh",
  "Ai có mã người mới cho mình xin với ạ",
  "Xin",
  "Còn group zalo nào báo deal k ad",
  "...",
  "K áp dc mã vd",
  "Bị lọc mất ùi",
  "Cs mà 50k đơn tới thiếu 0d ik bẹn",
  "Săn dữ z",
  "Tuyệt",
  "Xin",
  "Ngon ne",
  "Đã quá ạ",
  "Có mã 0đ cho gấu bông kh aa",
  "Xin ne",
  "Ngon",
  "Màu áo xinh z",
  "Lụm lẹ",
  "100k á",
  "Ship hơn 200😢",
  "Quá ship chán động quá😢",
  "Nhìn phí ship kiểu 😢",
  "Của tui ship 179=))",
  "Lụm",
  "Ngon",
  "Xuất sắc c ơi",
  "Dao này mã video áp cho ngành hàng nào thế ạ? Mã 50% tối đa 25k em không áp dc cho cái gì luôn 😅",
  "Xong hỏi ý có link gần tag mua gì cũng được chứ. Chỉ có ngồi nghỉ xem mua gì thôi 😂",
  "Sao mã video và live 50% tối đa 25k hết sạch à ad? Hay tk KIM CƯƠNG của em bị hạn chế nhở 😅, thật vô bổ cái level. Em dùng máy bạn em vẫn dc huhu",
  "Giờ ít canh ngày đôi săn sale thôi. Nói chung giờ mua se so với năm ngoài hết zui rồi 😏",
  "Haizz đợt này tui bị khóa 4acc liên",
  "Trải nghiệm lúc đó của em là 7h50 vào nhóm zalo tag @all vô đặt nha các bạn hiền iu dấu :)))), ban đầu nó còn có mã 50% tối đa 40k, tháng sau nó có mã 15% tối đa 100k húp trọn :>>",
  "Đợt có mã 50/70 ê hè từ sáng đến tối k hết",
  "Oai mn cho e hỏi sao e đặt trong shoppe video mà k hiện dc tag video cung k có mã nào luôn",
  "Phải gọi là ngày nào cũng lên đơn :)))",
  "Tất cả chỉ còn là kỷ niệm, dạo này Pee ket sí ghee",
  "Ngày nào cũng 4 nick mua âm ầm. Dấu ấn xếp thành hàng 😂",
  "Mã live t áp dc mỗi mã giảm 8% giảm chả dc bao nhiêu. Thôi mệt nghỉ phe. Giờ tích xu chứ chả mua dc cái gì",
  "Mọi người cho e hỏi mình dùng một mã 50k rồi có mất mãy cái còn lại không ạ",
  "Deal ngon quá, chốt luôn!",
  "Có mã giảm giá nào cho đơn này không nhỉ?",
  "Cho mình xin giá sản phẩm này với ạ.",
  "Bạn nào có link mua sản phẩm này không?",
  "Làm sao để mua được sản phẩm này với giá sale nhỉ?",
  "Xin thêm mã giảm giá để chốt đơn này nào.",
  "Ai có mã giảm giá cho mình xin với.",
  "Sản phẩm này giá bao nhiêu vậy?",
  "Mua sản phẩm này ở đâu thế?",
  "Có ai biết cách mua sản phẩm này không?",
  "Sale mạnh quá, phải chốt ngay thôi!",
  "Chia sẻ cho mình link sản phẩm với.",
  "Ai có kinh nghiệm mua hàng sale chỉ mình với.",
  "Deal này quá hời, không mua thì tiếc lắm.",
  "Mình cần mã giảm giá, ai có không?",
  "Xin giá sản phẩm này với các bạn ơi.",
  "Có ai biết link mua sản phẩm này không?",
  "Cách mua sản phẩm này như thế nào vậy?",
  "Sale sốc quá, phải tranh thủ chốt ngay.",
  "Cần thêm mã giảm giá để tiết kiệm hơn.",
  "Mã giảm giá này dùng được bao lâu?",
  "Giá sản phẩm này bao nhiêu các bạn?",
  "Mua ở đâu rẻ nhất nhỉ?",
  "Xin hướng dẫn cách mua sản phẩm này.",
  "Chốt đơn nhanh kẻo hết sale!",
  "Có mã giảm giá nào cho sản phẩm này không?",
  "Xin link mua sản phẩm này với ạ.",
  "Ai biết cách săn mã giảm giá không?",
  "Sale tốt quá, phải mua ngay thôi.",
  "Ai có mã giảm giá share mình với.",
  "Sản phẩm này giá thế nào vậy?",
  "Mua sản phẩm này ở đâu rẻ nhất?",
  "Xin hướng dẫn cách mua hàng sale.",
  "Deal này ngon quá, không thể bỏ qua.",
  "Cần mã giảm giá để mua sản phẩm này.",
  "Giá của sản phẩm này bao nhiêu?",
  "Ai có link mua sản phẩm này không?",
  "Xin cách mua sản phẩm này với.",
  "Sale đỉnh quá, phải chốt liền.",
  "Cần thêm mã giảm giá để mua hàng.",
  "Mã giảm giá này dùng ở đâu?",
  "Giá của sản phẩm này thế nào?",
  "Mua sản phẩm này ở đâu tốt nhất?",
  "Xin hướng dẫn cách mua sản phẩm.",
  "Chốt deal nhanh kẻo hết sale.",
  "Có mã giảm giá nào không mọi người?",
  "Xin link sản phẩm này với ạ.",
  "Ai biết cách săn mã không?",
  "Sale mạnh quá, phải mua ngay.",
  "Cần mã giảm giá gấp.",
  "Giá sản phẩm này bao nhiêu?",
  "Mua sản phẩm này ở đâu nhỉ?",
  "Xin hướng dẫn cách mua.",
  "Deal ngon quá, không thể bỏ qua.",
  "Cần mã giảm giá để mua sản phẩm này.",
  "Giá của sản phẩm này bao nhiêu?",
  "Ai có link mua sản phẩm này không?",
  "Xin cách mua sản phẩm này với.",
  "Sale đỉnh quá, phải chốt liền.",
  "Cần thêm mã giảm giá để mua hàng.",
  "Mã giảm giá này dùng ở đâu?",
  "Giá của sản phẩm này thế nào?",
  "Mua sản phẩm này ở đâu tốt nhất?",
  "Xin hướng dẫn cách mua sản phẩm.",
  "Chốt deal nhanh kẻo hết sale.",
  "Có mã giảm giá nào không mọi người?",
  "Xin link sản phẩm này với ạ.",
  "Ai biết cách săn mã không?",
  "Sale mạnh quá, phải mua ngay.",
  "Cần mã giảm giá gấp.",
  "Giá sản phẩm này bao nhiêu?",
  "Mua sản phẩm này ở đâu nhỉ?",
  "Xin hướng dẫn cách mua.",
  "Deal ngon quá, không thể bỏ qua.",
  "Cần mã giảm giá để mua sản phẩm này.",
  "Giá của sản phẩm này bao nhiêu?",
  "Ai có link mua sản phẩm này không?",
  "Xin cách mua sản phẩm này với.",
  "Sale đỉnh quá, phải chốt liền.",
  "Cần thêm mã giảm giá để mua hàng.",
];

export { commentsBanhBao, commentsShopeeSale };
